; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env]
platform = sonyspresense
board = spresense
framework = arduino
upload_command = ${platformio.packages_dir}/tool-spresense/flash_writer/windows/flash_writer -s -c $UPLOAD_PORT -b $UPLOAD_SPEED -d -n -s $SOURCE

[env:spresense_mainCore]
build_src_filter = +<main/>
lib_deps = 
	bblanchon/ArduinoJson@^6.21.3
	lovyan03/LovyanGFX@^1.2.7
build_flags =
    -D ARDUINOJSON_ENABLE_PROGMEM=0
board_upload.maximum_size = 786432
board_upload.maximum_ram_size = 786432

#  128K (131072),   256K (262144),   384K (393216),   512K (524288)
#  640K (655360),   768K (786432),   896K (917504),  1024K (1048576)
# 1152K (1179648), 1280K (1310720), 1408K (1441792), 1536K (1572864)

[env:spresense_subCore1]
build_flags = -DPIO_FRAMEWORK_ARDUINO_CORE_SUB_CORE_1
build_src_filter = +<sub1/>
lib_deps = 
    adafruit/Adafruit Unified Sensor@^1.1.15
    adafruit/Adafruit BusIO@^1.17.4
#   adafruit/Adafruit BNO055@^1.6.4 # modified locally

[env:spresense_subCore2]
build_flags = -DPIO_FRAMEWORK_ARDUINO_CORE_SUB_CORE_2
build_src_filter = +<sub2/>

[env:spresense_subCore3]
build_flags = -DPIO_FRAMEWORK_ARDUINO_CORE_SUB_CORE_3
build_src_filter = +<sub3/>
